name: Deploy Frontend to Vercel

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'holistica-frontend/**'

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./holistica-frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
        
      - name: Deploy to Vercel
        run: |
          # Install Vercel CLI
          npm install -g vercel@latest
          
          # Create vercel.json if it doesn't exist
          if [ ! -f "vercel.json" ]; then
            echo '{
              "version": 2,
              "buildCommand": "npm run build",
              "outputDirectory": "build",
              "framework": "create-react-app",
              "routes": [{"src": "/(.*)", "dest": "/index.html"}]
            }' > vercel.json
            echo "Created vercel.json configuration"
          fi
          
          # Deploy with explicit token
          echo "Deploying to Vercel..."
          vercel --prod --yes --token "${{ secrets.VERCEL_TOKEN }}"
          
          echo "✅ Vercel deployment complete"
